---
title: "Reading log files"
author: "Dr Simon Jackson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette will describe how to read a user's log files with various functions provided in the adapter package.

## Log files and folders

At the time this vignette was written, the adaptability simulation generated users' log files with particular structures and formats. It is important to understand this, as it guides how the reading functions work.

### How files and folders are arranged and formatted

A user's log-files directory (folder containing all of their log files) has three things in it:

- A file containing session information: `session.tsv`
- A file containing logs of discrete events: `events.tsv`
- A directory (folder): `streams/`
  - Within `streams/` there may be multiple files that each refer to a variable that was logged in a continuous/streaming fashion (every frame). For example, in this folder we might find `input_brake.tsv`, which is a continuous stream of the value of the driver's brake.

All log files are created in a tab-separated values (.tsv) format without headers. This helps to minimise file size and maximise compatability across software packages.

### The session file

The session file (`session.tsv`) contains general information about the session. For example, the local time when the simulation was started, and the user's id. It is effectively a key-value table. One column contains variables names, and a second contains its value.

### The events file

The events file (`events.tsv`) contains a log of discrete events that occur within the simulation. For example, the time at which a new lap begins, or every time the driver collides with an object, and so on. Each row logs a single event. Each row contains at least two columns. The first column is a timestamp of when the event occured (see [timestamp format](#timestamp-format)). The second column is the event name. Any other values that appear beyond these two columns provides some additional information about the event.

### Stream files

Files that appear in the `streams/` directory each log a particular variable every single frame of the simulation. These files are therefore reserved for variables like the accelerator, the steering angle, the velocity of the car, and so on. In these files, each row represents a variable's value at a particular point in time, and contains two columns. The first is a timestamp (see [timestamp format](#timestamp-format)). The second is the variable's value. The name of the file indicates the variable that is being logged.

### Timestamp format

Timestamps are generally formatted to be epoch time to 100th of a millisecond. Therefore, to convert this to regular epoch time (or some other time stamp), divide it by 100 (to get to millisecond epoch time), and do regular conversion.

## Functions for reading log files

The adapter package provides 


